#!/bin/bash

shopt -s globstar

DIR=$(cd $(dirname "$0"); pwd)
ROOT=$(cd "$DIR/.."; pwd)
cd "$ROOT"

json_license() {
    dir="$1"
    pkg=$(basename "$dir")
    license=$(cat "$dir"/LICENSE* "$dir"/license* 2>/dev/null)
    [ -z "$license" ] && [ -r "$dir"/package.json ] && {
        license=$(cat "$dir"/package.json | jq -r '.license')
    }
    jq -n \
       --arg pkg "$pkg" \
       --arg url "https://www.npmjs.com/package/$pkg" \
       --arg license "$license" \
       '{"package": $pkg, "url": $url, "license": $license}'
}

echo -n '['; sep=''
for dir in $(ls -d node_modules/*); do
    echo -n "$sep"; sep=','
    json_license "$dir"
done
echo ']'
