#!/bin/bash

DIR=$(cd $(dirname "$0"); pwd)
ROOT=$(cd "$DIR/.."; pwd)
cd "$ROOT"

json_license() {
    dir="$1"
    pkg="${dir#node_modules/}"
    license=$(cat "$dir"/LICENSE* "$dir"/license* 2>/dev/null)
    if [[ -z "$license" ]]; then
        if [[ -r "$dir"/package.json ]]; then
            license=$(cat "$dir"/package.json | jq -r '.license')
        else
            if [[ "$pkg" = "@"* ]]; then
                for d in $(ls -d "$dir"/*); do
                    json_license "$d"
                done
            fi
            return
        fi
    fi
    echo -n "$sep"; sep=','
    jq -n \
       --arg pkg "$pkg" \
       --arg url "https://www.npmjs.com/package/$pkg" \
       --arg license "$license" \
       '{"package": $pkg, "url": $url, "license": $license}'
}

echo -n '['; sep=''
for dir in $(ls -d node_modules/*); do
    json_license "$dir"
done
echo ']'
