name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # TODO: We need unit test or something

      - name: Image Build Test
        run: |
          node_version=$(cat .node-version)
          image=$(docker build -q --force-rm --build-arg NODE_VERSION=$node_version -t fireworqonsole .)
          docker run --rm $image -v
          docker image rm -f $image
